apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerador-de-nomes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerador-de-nomes
  template:
    metadata:
      labels:
        app: gerador-de-nomes
    spec:
      containers:
        - name: gerador-de-nomes
          image: rperin4/gerador-de-nomes:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: SQS_QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/419539974288/fila-nomes"
            - name: DYNAMODB_TABLE_NAME
              value: "Nomes-do-gerador"
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gerador-de-nomes-service
spec:
  selector:
    app: gerador-de-nomes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
