FROM python:3.9-slim

WORKDIR /app

COPY app.py .
COPY requirements.txt .
COPY templates/ ./templates
COPY static/ ./static

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "-u", "app.py"]
